### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by MaciekBaron** [nc-z/taffer#1]
Is it possible to use the graphics in this repo for another open-source project (e.g. to visualise something)? Are these graphics covered by some licence? Many thanks!

**Comment by nc-z** [comment]
The short answer is that I consider the license to be CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/), and you can use it as you like as long as you give me credit for the tileset.

The longer answer is that the copyright status of my work is slightly problematic: bitmap fonts aren't eligible for copyright in most of the world, although I'm not certain about the tiny graphics accompanying them. In addition, portions of my tileset are derived from other tilesets, and I have no way of knowing if those individuals used public domain code sheets or drew the graphics themselves, or if they're even eligible for copyright. This uncertainty is why I haven't specified a license.

Either way, I look forward to seeing what you do with it, and I'll be happy so long as credit is given somewhere. I specified in a comment elsewhere (https://www.reddit.com/r/dwarffortress/comments/1olywh/taffers_tilesets_graphics_version_13_released_new/cctp84c) that it is CC BY-SA (ShareAlike): this was a mistake.
